name: Docker

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build, Push and Deploy to Heroku
        uses: artofrawr/github-action-heroku@v1.0.0  # use the latest version of the action
        with:
          email: ${{ secrets.HEROKU_USERNAME }} # your heroku email
          api_key: ${{ secrets.HEROKU_API_KEY }} # your  heroku api key
          app_name: ${{ secrets.HEROKU_APP_NAME }} # you aplication name
          dockerfile: './Dockerfile' # set the path to the the Dockerfile
          process: 'web' # the process type you're deploying to
